## Transcript Comparison
Comparison of multiple Transcripts (Whisper & FHNW Model) to determine DIT and DAT material.

### Importts

In [6]:
import sys
import importlib
import pandas as pd
from pathlib import Path

SCRIPTS_DIR = Path.cwd() / "scripts" if (Path.cwd() / "scripts").exists() else Path.cwd()
sys.path.insert(0, str(SCRIPTS_DIR))
PROJECT_ROOT = SCRIPTS_DIR.parent

### Paths

In [7]:
PROJECT_ROOT = Path("__file__").resolve().parent.parent.parent.parent
ANALYSIS_DIR = PROJECT_ROOT / "samples" / "zurich_subset" / "stt-transcript-analysis"

WHISPER_SMALL = ANALYSIS_DIR / "whisper" / "whisper-small.tsv"
WHISPER_MEDIUM = ANALYSIS_DIR / "whisper" / "whisper-medium.tsv"
WHISPER_LARGE_V1 = ANALYSIS_DIR / "whisper" / "whisper-large-v1.tsv"
WHISPER_LARGE_V2 = ANALYSIS_DIR / "whisper" / "whisper-large-v2.tsv"
WHISPER_LARGE_V3 = ANALYSIS_DIR / "whisper" / "whisper-large-v3.tsv"
WHISPER_LARGE_V1_PROMPTED = ANALYSIS_DIR / "whisper" / "whisper-large-v1-prompted.tsv"
WHISPER_LARGE_V2_PROMPTED = ANALYSIS_DIR / "whisper" / "whisper-large-v2-prompted.tsv"
WHISPER_LARGE_V3_PROMPTED = ANALYSIS_DIR / "whisper" / "whisper-large-v3-prompted.tsv"
FHNW_LARGE = ANALYSIS_DIR / "fhnw" / "fhnw-large.tsv"

### Merge transcripts to compare

In [8]:
df_whisper_small = pd.read_csv(WHISPER_SMALL, sep="\t", encoding="utf-8-sig")
df_whisper_medium = pd.read_csv(WHISPER_MEDIUM, sep="\t", encoding="utf-8-sig")
df_whisper_large_v1 = pd.read_csv(WHISPER_LARGE_V1, sep="\t", encoding="utf-8-sig")
df_whisper_large_v2 = pd.read_csv(WHISPER_LARGE_V2, sep="\t", encoding="utf-8-sig")
df_whisper_large_v3 = pd.read_csv(WHISPER_LARGE_V3, sep="\t", encoding="utf-8-sig")
df_whisper_fhnw = pd.read_csv(FHNW_LARGE, sep="\t", encoding="utf-8-sig")

from functools import reduce

frames = [
    df_whisper_fhnw[["path", "sentence", "transcript"]].rename(columns={"transcript": "transcript_fhnw"}),
    df_whisper_large_v1[["path", "transcript"]].rename(columns={"transcript": "transcript_v1"}),
    df_whisper_large_v2[["path", "transcript"]].rename(columns={"transcript": "transcript_v2"}),
    df_whisper_large_v3[["path", "transcript"]].rename(columns={"transcript": "transcript_v3"}),
    df_whisper_medium[["path", "transcript"]].rename(columns={"transcript": "transcript_medium"}),
    df_whisper_small[["path", "transcript"]].rename(columns={"transcript": "transcript_small"}),
]

df_transcripts = reduce(lambda left, right: pd.merge(left, right, on="path", how="inner"), frames)
df_transcripts.head()

,path,sentence,transcript_fhnw,transcript_v1,transcript_v2,transcript_v3,transcript_medium,transcript_small
0,clips/300bb931-79ae-40ec-b989-3efd5e83f4c2/83c...,Insgesamt habe ich einige Hunderttausend Frank...,Insgesamt habe ich einige Hunderttausend Frank...,Insgesamt habe ich einige Hunderttausend Frank...,Insgesamt habe ich einige hunderttausend Frank...,Insgesamt habe ich einige hunderttausend Frank...,Insgesamt habe ich einige 100'000 Franken verl...,Insgesamt habe ich einige hunderttausend Frank...
1,clips/6e084270-8d26-43d9-ba69-5e8ee793ab8c/dca...,Welche Rolle hatte Rosenberg während des Holoc...,Welche Rolle hatte Rosenberg während des Holoc...,Welche Rolle hätte Roseberg während des Holoca...,Welche Rolle hatte Rausenberg während des Holo...,Welche Rolle hatte Rosenberg während dem Holoc...,Welche Rolle hatte Rosenberg während des Holoc...,Welche Rolle hätte ein Rosenberg während des H...
2,clips/6858a37b-edd0-4fdf-871c-96d3b1bd3e21/82f...,Das ist angesichts aller schlechten Optionen d...,Das ist angesichts aller schlechten Optionen d...,Das ist angesichts aller schlechter Optionen d...,Das ist angesichts aller schlechten Optionen d...,Das ist angesichts aller schlechten Optionen d...,Das ist angesichts aller schlechten Optionen d...,Das ist angesichts von allen schlechten Option...
3,clips/c4c03e6f-50a2-4d24-ae88-caf3032798fa/a21...,Ebenfalls keinen Sieg durfte die AC Milan feiern.,Ebenfalls keinen Sieg durfte AC Milan feiern.,Ebenfalls kein Sieg hat AC Milan feiern dürfen.,Ebenfalls kein Sieg durfte AC Milan feiern.,Ebenfalls kein Sieg durfte AC Milan feiern.,Ebenfalls kein Sieg durfte AC Milan feiern.,Aber falls kein Sieg hat AC Milan dürfen vier.
4,clips/f877ee50-af2b-423b-bdda-0cc406032c45/4e5...,Viele Fussballfans haben die Alte Reithalle un...,Viele Fussballfans haben die alte Reithalle un...,Viele Fussballfans haben die Alt-Rheintale unt...,Viele Fussballfans haben die Alt-Rheintaler un...,Viele Fussballfans haben die Altritalen unters...,Viele Fussballfans haben die Alt-Rheintaler un...,Viele Fußballfans haben die Alldriehtale unter...

### Prompted

In [9]:
df_whisper_large_v1_prompted = pd.read_csv(WHISPER_LARGE_V1_PROMPTED, sep="\t", encoding="utf-8-sig")
df_wishper_large_v2_prompted = pd.read_csv(WHISPER_LARGE_V2_PROMPTED, sep="\t", encoding="utf-8-sig")
df_whisper_large_v3_prompted = pd.read_csv(WHISPER_LARGE_V3_PROMPTED, sep="\t", encoding="utf-8-sig")

from functools import reduce

frames = [
    df_whisper_large_v1_prompted[["path", "sentence", "transcript"]].rename(columns={"transcript": "transcript_v1_prompted"}),
    df_wishper_large_v2_prompted[["path", "transcript"]].rename(columns={"transcript": "transcript_v2_prompted"}),
    df_whisper_large_v3_prompted[["path", "transcript"]].rename(columns={"transcript": "transcript_v3_propmpted"}),
]

df_prompted = reduce(lambda left, right: pd.merge(left, right, on="path", how="inner"), frames)
df_prompted.head()

,path,sentence,transcript_v1_prompted,transcript_v2_prompted,transcript_v3_propmpted
0,clips/300bb931-79ae-40ec-b989-3efd5e83f4c2/83c...,Insgesamt habe ich einige Hunderttausend Frank...,Insgesamt han ich einige hunderttausig Franken...,Insgesamt hann ich einige hunderttausend Frank...,Insgesamt hann ich einige hunderttusig Franken...
1,clips/6e084270-8d26-43d9-ba69-5e8ee793ab8c/dca...,Welche Rolle hatte Rosenberg während des Holoc...,Welch Rolle hätte Ruseberg während dem Holocau...,Wäli Rolle hätt de Ruseberg wärend dem Holocas...,Weli Rolle hätte Rosenberg während dem Holocau...
2,clips/6858a37b-edd0-4fdf-871c-96d3b1bd3e21/82f...,Das ist angesichts aller schlechten Optionen d...,Das isch angesichts vo allner schlechter Optio...,Das isch angesichts vo allne schlechte Optione...,Das isch angesichts vo allne schlechte Optione...
3,clips/c4c03e6f-50a2-4d24-ae88-caf3032798fa/a21...,Ebenfalls keinen Sieg durfte die AC Milan feiern.,Äbefalls kein Sieg hät AC-Milan därfe füehre.,Äbefalls kein Sieg hät AC-Milan dörfe füehre.,Äbefalls kein Sieg hät AC-Milan därfe füehre.
4,clips/f877ee50-af2b-423b-bdda-0cc406032c45/4e5...,Viele Fussballfans haben die Alte Reithalle un...,Viele Fussballfans hend die Altreitale unterst...,Viele Fussballfans händ die Alt-Rheintale unte...,Viele Fussballfäns händ die all drei Thale unt...

## Learning

- prompted is not what we want
- wav2vec2 doesn't transcribe well enough
- whisper-v2 still keeps dialect specific words, sometimes misinterprets them

=> DAT: FHNW, DIT: whisper-v2